# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('git_repo', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=400)),
                ('description', models.TextField()),
            ],
        ),
    ]
